# 1. Importanto os módulos

In [1]:
# Pandas para a análise, manipulação e visualização dos dados
import pandas as pd

# Numpy para manipução dos dados
import numpy as np

# Seaborn e Matplotlib para geração de gráficos
import seaborn as sns
import matplotlib.pyplot as plt

# Os para a acessar os diretórios do sistema
import os

# 2. Estrutura dos dados

In [2]:
# Importando o nome dos arquivos
nome_arquivo_csv = os.listdir()[1]

# Importando o arquivo .csv para a Python com Pandas
df = pd.read_csv(nome_arquivo_csv)
df.head()

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,$60K - $80K,blue,39,5,3,1,"12.691,51","1.144,90",42
1,818770008,0,49,F,5,mestrado,solteiro,menos que $40K,blue,44,6,2,1,"8.256,96","1.291,45",33
2,713982108,0,51,M,3,mestrado,casado,$80K - $120K,blue,36,4,0,1,"3.418,56","1.887,72",20
3,769911858,0,40,F,4,ensino medio,na,menos que $40K,blue,34,3,1,4,"3.313,03","1.171,56",20
4,709106358,0,40,M,3,sem educacao formal,casado,$60K - $80K,blue,21,5,0,1,"4.716,22","816,08",28

In [3]:
# Analisando as informações contidas nas colunas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       10127 non-null  int64
 1   default                  10127 non-null  int64
 2   idade                    10127 non-null  int64
 3   sexo                     10127 non-null  object
 4   dependentes              10127 non-null  int64
 5   escolaridade             10127 non-null  object
 6   estado_civil             10127 non-null  object
 7   salario_anual            10127 non-null  object
 8   tipo_cartao              10127 non-null  object
 9   meses_de_relacionamento  10127 non-null  int64
 10  qtd_produtos             10127 non-null  int64
 11  iteracoes_12m            10127 non-null  int64
 12  meses_inativo_12m        10127 non-null  int64
 13  limite_credito           10127 non-null  object
 14  valor_transacoes_12m     10127 non-null  object
 15  qtd_transacoes_12m       10127 non-null  int64
dtypes: int64(9), object(7)
memory usage: 1.2+ MB

## Corrigindo dados faltantes

Observamos com .info() que todas as variáveis possuem o mesmo número de entradas, o que é interessante. Porém, essa informação está errada pois sabemos que algumas das entradas com a informação "na" são na verdade dados faltantes. Por isso, vamos converter todos os "na" em NuN (np.nan).

In [4]:
'''
  Laço que itera os nomes das colunas, que serão usadas para selecionar as
  variáveis e convereter, na função lambda, "na" para NuN (np.nan).
'''
for coluna in df.columns:
  df[coluna] = df[coluna].apply(lambda valor: np.nan if valor == "na" else valor)

df.head()

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,$60K - $80K,blue,39,5,3,1,"12.691,51","1.144,90",42
1,818770008,0,49,F,5,mestrado,solteiro,menos que $40K,blue,44,6,2,1,"8.256,96","1.291,45",33
2,713982108,0,51,M,3,mestrado,casado,$80K - $120K,blue,36,4,0,1,"3.418,56","1.887,72",20
3,769911858,0,40,F,4,ensino medio,NaN,menos que $40K,blue,34,3,1,4,"3.313,03","1.171,56",20
4,709106358,0,40,M,3,sem educacao formal,casado,$60K - $80K,blue,21,5,0,1,"4.716,22","816,08",28

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       10127 non-null  int64
 1   default                  10127 non-null  int64
 2   idade                    10127 non-null  int64
 3   sexo                     10127 non-null  object
 4   dependentes              10127 non-null  int64
 5   escolaridade             8608 non-null   object
 6   estado_civil             9378 non-null   object
 7   salario_anual            9015 non-null   object
 8   tipo_cartao              10127 non-null  object
 9   meses_de_relacionamento  10127 non-null  int64
 10  qtd_produtos             10127 non-null  int64
 11  iteracoes_12m            10127 non-null  int64
 12  meses_inativo_12m        10127 non-null  int64
 13  limite_credito           10127 non-null  object
 14  valor_transacoes_12m     10127 non-null  object
 15  qtd_transacoes_12m       10127 non-null  int64
dtypes: int64(9), object(7)
memory usage: 1.2+ MB

Com isso observamos que as variáveis abaixo tem menos entradas que as demais colunas:
- escolaridade
- estado_civil
- salario_anual

In [6]:
'''
  Analisando a porcentagem de cobertura dos dados no banco,
  em cada um das variáveis que contém dados faltando
'''
num_escolaridade = df["escolaridade"].notna().sum() / len(df)
num_estado_civil = df["estado_civil"].notna().sum() / len(df)
num_salario_anual = df["salario_anual"].notna().sum() / len(df)

print(f"Escolaridade: {num_escolaridade * 100:.2f}%")
print(f"Estado civil: {num_estado_civil * 100:.2f}%")
print(f"Salario anual: {num_salario_anual * 100:.2f}%")

Escolaridade: 85.00%
Estado civil: 92.60%
Salario anual: 89.02%

In [7]:
print(f"Porcentagem de perda, eliminando os dados faltantes: {round((len(df.dropna()) / len(df) - 1) * -100, 2)}%")

Porcentagem de perda, eliminando os dados faltantes: 30.08%

Observamos que a variável com menos dados têm 85% de cobertura do número total de entradas. Entendemos que essa porcentagem pode ser significativa, por isso não vamos apenas remover do conjunto de dados faltantes, o que acarretaria em uma perda de 30%. Para equalizar essa condição, vou **substituir os valores faltando pelas cotegorias já existentens, observando a mesma proporção**.

In [8]:
# FreqU~encia das categorias na variável escolaridade
round((df['escolaridade'].value_counts(normalize=True)), 2)

mestrado               0.36
ensino medio           0.23
sem educacao formal    0.17
graduacao              0.12
doutorado              0.11
Name: escolaridade, dtype: float64

In [9]:
def completa_na_por_frequencia(df: pd.DataFrame, coluna: str) -> pd.DataFrame|str:
  '''
    Função que completa os valores faltantes de uma variável de uma DataFrame
    por valores já presentes na variável, obdesendo a proporção entre eles.
    :param df (pd.DataFrame): DataFrame contendo os dados;
    :param coluna (str): Nome da variável contendo NuN;
    :return df (pd.DataFrame): DataFrame com os dados substituídos;
  '''
  try:
    # Variável que recebe a frequência relativa e o nome das categorias
    data_transforme = df[coluna].value_counts(normalize=True)

    # Número de NuN
    n_amostras = len(df) - len(df[coluna].dropna())

    # Série que é formada pela escolha randômica, usando numpy, das categorias
    categorias = pd.Series(
        data=np.random.choice(
            data_transforme.index,
            p=data_transforme.values,
            size=n_amostras
        ),
        index=df[df[coluna].isna()].index
    )

    # Substituição do NuN pelas categorias
    df.loc[categorias.index, coluna] = categorias.values
    return df
  except Exception as erro:
    return erro

In [10]:
df = completa_na_por_frequencia(df=df, coluna="escolaridade")
df = completa_na_por_frequencia(df=df, coluna="estado_civil")
df = completa_na_por_frequencia(df=df, coluna="salario_anual")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       10127 non-null  int64
 1   default                  10127 non-null  int64
 2   idade                    10127 non-null  int64
 3   sexo                     10127 non-null  object
 4   dependentes              10127 non-null  int64
 5   escolaridade             10127 non-null  object
 6   estado_civil             10127 non-null  object
 7   salario_anual            10127 non-null  object
 8   tipo_cartao              10127 non-null  object
 9   meses_de_relacionamento  10127 non-null  int64
 10  qtd_produtos             10127 non-null  int64
 11  iteracoes_12m            10127 non-null  int64
 12  meses_inativo_12m        10127 non-null  int64
 13  limite_credito           10127 non-null  object
 14  valor_transacoes_12m     10127 non-null  object
 15  qtd_transacoes_12m       10127 non-null  int64
dtypes: int64(9), object(7)
memory usage: 1.2+ MB

In [11]:
# FreqU~encia das categorias na variável escolaridade
round((df['escolaridade'].value_counts(normalize=True)), 2)

mestrado               0.37
ensino medio           0.23
sem educacao formal    0.17
graduacao              0.12
doutorado              0.11
Name: escolaridade, dtype: float64

In [12]:
'''
  Analisando a porcentagem de cobertura dos dados no banco,
  em cada um das variáveis que contém dados faltando
'''
num_escolaridade = df["escolaridade"].notna().sum() / len(df)
num_estado_civil = df["estado_civil"].notna().sum() / len(df)
num_salario_anual = df["salario_anual"].notna().sum() / len(df)

print(f"Escolaridade: {num_escolaridade * 100:.2f}%")
print(f"Estado civil: {num_estado_civil * 100:.2f}%")
print(f"Salario anual: {num_salario_anual * 100:.2f}%")

Escolaridade: 100.00%
Estado civil: 100.00%
Salario anual: 100.00%

### Conclusão

Foi observado que no conjunto de dados, alguns valores estavam faltando. A simples retirada levaria a uma perda de ~30% dos dados, o que julgamos inadequado.

Foi resolvido substituir os valores faltantes pelas mesmas categorias já presentes no conjunto de dados, obdesendo a frequência relativa na variável.

Assim, foi obtido um conjunto de dados sem valores faltantes.

## Tipificação das variáveis

In [13]:
df.dtypes

id                          int64
default                     int64
idade                       int64
sexo                       object
dependentes                 int64
escolaridade               object
estado_civil               object
salario_anual              object
tipo_cartao                object
meses_de_relacionamento     int64
qtd_produtos                int64
iteracoes_12m               int64
meses_inativo_12m           int64
limite_credito             object
valor_transacoes_12m       object
qtd_transacoes_12m          int64
dtype: object

Algumas das variáveis não correspondm com as classes (tipos) dos dados usados para armazenar na DataFrame. As variáveis abaixo deveriam ser *category*:

- sexo
- escolaridade
- estado_civil
- salario_anual
- tipo_cartao

As variáveis abaixo deveriam ser *float*:
- limite_credito
- valor_transacoes_12m

Além disso, a variável **default**, que indica o pagamento ou sua falta, deveria ser *bool*.

In [14]:
# Instanciando uma dicionário com as colunas e as novas classes da DataFrame
novos_tipos = {
    "default":       "bool",
    "sexo":          "category",
    "escolaridade":  "category",
    "estado_civil":  "category",
    "salario_anual": "category",
    "tipo_cartao":   "category",
}
novos_tipos

{'default': 'bool',
 'sexo': 'category',
 'escolaridade': 'category',
 'estado_civil': 'category',
 'salario_anual': 'category',
 'tipo_cartao': 'category'}

In [15]:
# Convertendo para as novas classes usando dicionário
df = df.astype(novos_tipos)

# Convertendo as colunas para float
funcao_convert = lambda x: float(x.replace(".","").replace(",","."))
df["limite_credito"] = df["limite_credito"].apply(funcao_convert)
df["valor_transacoes_12m"] = df["valor_transacoes_12m"].apply(funcao_convert)
df.dtypes

id                            int64
default                        bool
idade                         int64
sexo                       category
dependentes                   int64
escolaridade               category
estado_civil               category
salario_anual              category
tipo_cartao                category
meses_de_relacionamento       int64
qtd_produtos                  int64
iteracoes_12m                 int64
meses_inativo_12m             int64
limite_credito              float64
valor_transacoes_12m        float64
qtd_transacoes_12m            int64
dtype: object

In [16]:
df.select_dtypes(include=['int64', "float64"]).head()

,id,idade,dependentes,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,45,3,39,5,3,1,12691.51,1144.90,42
1,818770008,49,5,44,6,2,1,8256.96,1291.45,33
2,713982108,51,3,36,4,0,1,3418.56,1887.72,20
3,769911858,40,4,34,3,1,4,3313.03,1171.56,20
4,709106358,40,3,21,5,0,1,4716.22,816.08,28

In [17]:
df.select_dtypes(exclude=['int64', "float64"]).head()

   default sexo         escolaridade estado_civil   salario_anual tipo_cartao
0    False    M         ensino medio       casado     $60K - $80K        blue
1    False    F             mestrado     solteiro  menos que $40K        blue
2    False    M             mestrado       casado    $80K - $120K        blue
3    False    F         ensino medio       casado  menos que $40K        blue
4    False    M  sem educacao formal       casado     $60K - $80K        blue

### Conclusão

O conjunto de dados apresentava algumas colunas que continham informações que não condiziam com a classe (tipo) de variável.

Foram substituídos pelas classes mais propícias por variável.

# Análise dos dados

## Medidas resumo

In [18]:
df.iloc[:,1:].select_dtypes(include=['int64', "float64"]).describe().T

,count,mean,std,min,25%,50%,75%,max
idade,10127.0,46.325960,8.016814,26.00,41.000,46.00,52.000,73.00
dependentes,10127.0,2.346203,1.298908,0.00,1.000,2.00,3.000,5.00
meses_de_relacionamento,10127.0,35.928409,7.986416,13.00,31.000,36.00,40.000,56.00
qtd_produtos,10127.0,3.812580,1.554408,1.00,3.000,4.00,5.000,6.00
iteracoes_12m,10127.0,2.455317,1.106225,0.00,2.000,2.00,3.000,6.00
meses_inativo_12m,10127.0,2.341167,1.010622,0.00,2.000,2.00,3.000,6.00
limite_credito,10127.0,8632.440165,9088.788041,1438.00,2555.355,4549.42,11068.175,34516.99
valor_transacoes_12m,10127.0,4404.583047,3397.128078,510.16,2155.825,3899.59,4741.310,18484.93
qtd_transacoes_12m,10127.0,64.858695,23.472570,10.00,45.000,67.00,81.000,139.00

In [19]:
df.iloc[:,1:].select_dtypes(exclude=['int64', "float64"]).describe().T

               count unique             top  freq
default        10127      2           False  8500
sexo           10127      2               F  5358
escolaridade   10127      5        mestrado  3712
estado_civil   10127      3          casado  5066
salario_anual  10127      5  menos que $40K  3981
tipo_cartao    10127      4            blue  9436